{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    {{- if eq .Values.rollout.strategy "canary" }}
    canary:
      canaryService: {{ .Values.service.name }}-canary
      stableService: {{ .Values.service.name }}-stable
      steps:
        - setWeight: 20
        - pause: {duration: 2m}
        - setWeight: 50
        - pause: {duration: 2m}
        - setWeight: 80
        - pause: {duration: 2m}
    {{- else if eq .Values.rollout.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ .Values.service.name }}
      previewService: {{ .Values.service.name }}-preview
      autoPromotionEnabled: false
    {{- end }}
---
{{- if eq .Values.rollout.strategy "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-canary
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-stable
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
{{- else if eq .Values.rollout.strategy "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-preview
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
{{- end }}
{{- end }}
