apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: observability
  labels:
    environment: dev
    service: backend
spec:
  project: default
  
  source:
    repoURL: https://github.com/Softbank-Hackathon-2025-Team-Yellow/runna-cicd
    targetRevision: main
    path: helm/charts/platform-service
    helm:
      valueFiles:
        - ../../values/values-backend-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # HPA가 관리하는 경우 무시
